site_name: adaXT

repo_url: https://github.com/NiklasPfister/adaXT
edit_uri: '?query=root/path/docs/'
watch: [mkdocs.yml, src/adaXT]
site_description: adaptable Decision Trees and Random Forests

plugins:
  - search:
  - autorefs:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_bases: false
            # Filters off all private methods defined with __, when importing
            filters: ["!__.*"]
            show_source: false
            show_root_heading: false

theme:
  name: "material"
  features:
    - navigation.sections
    - navigation.expand
    - content.code.annotate
    - content.code.copy
    - content.tooltips

  # Adding dark mode
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

# Navigation bar on the left
nav:
  - Welcome: index.md
  - API reference:
    - DecisionTree: decision_tree/tree/DecisionTree.md
    - criteria: decision_tree/criteria/criteria.md
    - tree_utils: decision_tree/utils/tree_utils.md
  - User Guide:
    - Decision Tree:
      - Creating a tree: decision_tree/examples/creatingATree.md
      - Creating a criteria: decision_tree/examples/creatingACriteria.md

# For setting up math and code blocks
markdown_extensions:
  # Math block setup
  - pymdownx.arithmatex:
      generic: true

  - toc:
      permalink: "#"


  # Code block setup
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Also for math
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js