site_name: adaXT
site_url: https://niklaspfister.github.io/adaXT/

repo_url: https://github.com/NiklasPfister/adaXT
repo_name: 'adaXT'
edit_uri: '?query=root/path/docs/'
watch: [mkdocs.yml, README.md, src/adaXT]
site_description: Adaptable and Extendable Decision Trees


plugins:
  - search:
  - autorefs:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_bases: false
            # Filters off all private methods defined with __, when importing
            filters: ["!^_"]
            show_source: false
            show_root_heading: false
            merge_init_into_class: yes
            show_docstring_attributes: true
            line_length: 60
            separate_signature: true

theme:
  name: "material"
  features:
    - navigation.sections
    - navigation.expand
    - content.code.annotate
    - content.code.copy
    - content.tooltips

  # Adding dark mode
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

# Navigation bar on the left
nav:
  - Overview: index.md
  - User Guide:
    - Decision trees:
      - Getting started: user_guide/getting_started.md
      - Creating custom criteria: user_guide/creatingCriteria.md
    - Random Forest:
      - Chosing n_jobs parameter: RandomForest/user_guide/chosing_n_jobs.md
  - API reference:
    - DecisionTree: api_docs/DecisionTree.md
    - Criteria: api_docs/Criteria.md
    - LeafBuilder: api_docs/LeafBuilder.md
    - Prediction: api_docs/Prediction.md
    - Splitter: api_docs/Splitter.md
    - Tree utilities: api_docs/tree_utils.md

# For setting up math and code blocks
markdown_extensions:
  # Math block setup
  - pymdownx.arithmatex:
      generic: true

  - toc:
      permalink: "#"

  # Code block setup
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.snippets:
# Also for math
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
