name: Cython-linting

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - main
      - Development
  workflow_dispatch:

jobs:
  test_lint:
    name: Cython-linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: |
          python -m pip install ruff cython-lint

      - name: Cython Linting
        run: |
          cython-lint src/* --max-line-length=127

